title: Andrea Lopera
logo: /assets/Andee.png
description: "Hi! I’m Andrea, a data scientist with a background in industrial production, education analytics, and process optimization. I specialize in transforming messy systems into streamlined, data-informed workflows that drive operational clarity and performance. My portfolio blends machine learning, business intelligence, and operations strategy—centered on real-world impact across sectors like manufacturing, energy, and education." 
show_downloads: true
theme: jekyll-theme-minimal
